RedHatProductSecurity/griffon

- .github/workflows/main.yml
- adrs/0001-cli-design.md
- griffon/service_layer/core_queries.py
First iteration of design of CLI ... which the existing codebase has a skeleton in place already - but everything up for discussion.
Note- will set up review meeting
> draft adr for cli design

- .github/workflows/main.yml
- griffon/commands/queries.py
- griffon/services/core_queries.py
- griffon/services/exp.py
> test for ci

- griffon/autocomplete/__init__.py
- griffon/commands/entities.py
- griffon/services/core_queries.py
**Note:** users will have to reinstall corgi bindings after this.
> Minor:  updated corgi bindings and various sundry

- griffon/commands/queries.py
- griffon/services/core_queries.py
- griffon/services/exp.py
Retrieve a list of components affected by a CVE.
```
>  griffon service queries components-affected-by-cve --cve-id CVE-2022-43404
```
Filter by affect resolution:
```
>  griffon service queries components-affected-by-cve --cve-id CVE-2022-43404 --resolution OOSS
```
> add service queries components-affected-by-cve

- griffon/cli.py
- griffon/commands/queries.py
- griffon/commands/reports.py
- griffon/services/core_reports.py
forgot to add some files, which also enables **products-affected-by-cve**
```
> griffon service queries products-affected-by-cve --cve-id CVE-2022-43406
```
> Minor: forgot to add files

- .github/workflows/main.yml
- Makefile
- griffon/commands/process.py
- griffon/commands/queries.py
- griffon/output.py
- griffon/services/__init__.py
- griffon/services/core_process.py
- griffon/services/core_queries.py
- griffon/services/core_reports.py
- requirements/dev.in
- requirements/dev.txt
- tox.ini
Added some typing, refined service to accept params (instead of whole ctx click context), a bunch of minor fixes
> Service refactor

- Containerfile
- Makefile
- griffon/commands/manage.py
- griffon/commands/process.py
- griffon/commands/queries.py
- griffon/commands/reports.py
- griffon/services/__init__.py
- griffon/services/core_queries.py
- griffon/services/core_reports.py
- scripts/smoke-tests.sh
- tests/test_reports.py
* added minimal container (still requires some decisions)
* final round of services refactoring
* renamed service queries for brevity
* added smoke test script
> Add container and various sundry

- griffon/__init__.py
- griffon/commands/queries.py
- griffon/output.py
- scripts/smoke-tests.sh
minimal text formatting - for now we choose to display full purl ... that may prove to be too verbose for some.
> GRIF-19, GRIF-38 - first pass at implementing text format

- .github/workflows/container.yml
- Containerfile
- Makefile
- docs/user_guide.md
- files/.zshrc
This PR provides a development container of the griffon CLI. Updated user docs on how to build and invoke.
**Note** - When we do a release we should build some variation of this
> GRIF-48 implement development container

- Makefile
- docs/user_guide.md
- griffon/cli.py
- griffon/commands/entities.py
- griffon/commands/queries.py
- griffon/output.py
- griffon/services/core_queries.py
- requirements/base.in
- requirements/base.txt
- requirements/dev.txt
- requirements/test.txt
- setup.py
and migrate to using pypi component-registry-bindings module
> Text format refinements

- .github/workflows/build.yml
- .github/workflows/container.yml
- .github/workflows/lint.yml
- LICENSE
- Makefile
- griffon/__init__.py
- griffon/cli.py
- griffon/commands/entities.py
- griffon/commands/queries.py
- griffon/output.py
- griffon/services/core_queries.py
- requirements/dev.txt
- requirements/test.in
- requirements/test.txt
- setup.py
- tests/features/IR.feature
- tests/features/steps/ir_steps.py
- tox.ini
* added build target CI
* added initial acceptance tests (using behave)
* added --no-color top level option
* added --no-progress-bar top level option
> Enhance testing

- griffon/cli.py
- griffon/commands/plugin_commands.py
- tests/test_plugins.py
just moving the 'furniture' around a little bit.
> Minor: reorg plugins

- griffon/__init__.py
Added
first experimental release to the PyPI
> bump release to 0.0.1

- docs/tutorial.md
- griffon/commands/queries.py
- griffon/services/core_queries.py
- tests/features/product-components.feature
- tests/features/product-summary.feature
- tests/features/products-contain-component.feature
- tests/features/steps/ir_steps.py
All features should get an acceptance test.
> Product summary feature test

- docs/tutorial.md
- griffon/commands/queries.py
- tests/features/product-manifest.feature
- tests/features/steps/ir_steps.py
enables product-manifest command
```
> griffon service product-manifest ansible_automation_platform-2.3 --spdx-json
```
> fix product-manifest

- griffon/commands/plugins/cvelib.py
- griffon/services/core_queries.py
experimental plugin integrating cvelib
> Cvelib plugin

- griffon/output.py
- griffon/services/core_queries.py
make --search-enabled-url search 'related_url' field as well (and return both root and deps).
> griffon service products-contain-component webkitgtk --search-related-url
> enable --search-related-url on products-contain-component

- griffon/commands/configure.py
- griffon/commands/entities.py
- griffon/commands/queries.py
Provide nascent component summary
> griffon service component-summary grafana
> add component-summary

- griffon/commands/docs.py
- griffon/commands/queries.py
> griffon service products-contain-component -s IPMItool --sfm2-flaw-id 2009389 --flaw-mode replace
> griffon service products-contain-component -s IPMItool --sfm2-flaw-id 2009389 --flaw-mode add
> where we add affect add/remove

- docs/tutorial.md
- griffon/__init__.py
- griffon/cli.py
- griffon/commands/configure.py
- griffon/output.py
- griffon/services/core_queries.py
- griffon/static/default_griffonrc
- setup.py
- tests/test_unit.py
Define default_profile in .griffonrc or supply as commandline option to exclude files
> griffon --profile latest service products-contain-component webkitgtk
Choose 'cloud' profile
> griffon --profile cloud service product-summary ansible
Choose 'all' profile for effectively no excludes
> griffon --profile all service product-summary ansible
> Enhance griffon dotfile to define profiles with excludes

- griffon/commands/queries.py
- griffon/services/core_queries.py
When griffon encounters a Bad Gateway error it blows up any downstream parsing ... this fix mitigates the problem which will ultimately be fixed in underlying service.
> GRIF-68 - mitigate Bad Gateway issues

- CHANGELOG.md
- griffon/commands/configure.py
- griffon/commands/plugin_commands.py
- griffon/commands/plugins/cve_mitre.py
- griffon/static/default_griffonrc
default .griffonrc now supplies a custom_plugin_dir where one can set a directory to pick up user custom plugins.
also added a cve_mitre plugin to retrieve CVE from mitre website.
> add custom plugin directory

- CHANGELOG.md
- requirements/base.in
- requirements/base.txt
- requirements/dev.txt
- requirements/test.txt
pegged 
* component-registry-bindings==1.3.1 
* osidb-bindings=3.0.0
> peg binding versions

- CHANGELOG.md
- docs/tutorial.md
- griffon/commands/queries.py
- griffon/commands/reports.py
- griffon/services/core_reports.py
Generate license report for a specific Product Stream:
> griffon service report-license ansible_automation_platform-2.2
Generate license report for a specific Component:
> griffon service report-license --purl "pkg:oci/redhat/ubi9-container@sha256:f6920213ae98d811051a31c80cefc31cd88206ece680f337b7b67f5e4a4fc0fd?arch=aarch64&repository_url=registry.redhat.io/ubi9&tag=9.1.0-1782"
>  GRIF-60: implement license report operation

- CHANGELOG.md
- griffon/services/core_queries.py
- requirements/base.in
- requirements/base.txt
- requirements/dev.txt
- requirements/test.txt
which also requires update to component-registry-bindings dependency (to v1.3.2)
> GRIF-85: fix --search-upstreams

- griffon/commands/entities.py
- griffon/output.py
enhanced to
emit version and shortern sha256
>griffon service product-components rhosdt-2
and this will emit nvr and download_url
>griffon -v  service product-components rhosdt-2
> GRIF-83 enhance product-components

- griffon/commands/entities/corgi.py
> add products, product-versions, product-variants and channels

- CHANGELOG.md
- griffon/commands/plugins/semgrep.py
- tests/test_plugins.py
To install semgrep python module first:
> griffon plugins semgrep setup
then
> griffon plugins semgrep scan {some directory}
> add simple semgrep plugin

- CHANGELOG.md
- docs/user_guide.md
- griffon/__init__.py
- griffon/commands/entities/__init__.py
- griffon/commands/entities/community_component_registry.py
- griffon/commands/entities/osidb.py
- griffon/services/core_queries.py
- scripts/smoke-tests.sh
- tests/test_entities.py
- tests/test_manage.py
> griffon entities community-component-registry
>griffon service products-contain-component --search-community --search-all curl
> Enable community components entity search

- griffon/__init__.py
- griffon/commands/queries.py
- griffon/output.py
- griffon/services/core_queries.py
- requirements/base.in
- requirements/base.txt
- requirements/dev.txt
- requirements/test.txt
> griffon service components-affected-by-flaw CVE-2022-3510
> griffon service products-affected-by-flaw CVE-2022-3510
> griffon service product-flaws cost-management --flaw-state NEW --affectedness AFFECTED
> griffon service component-flaws python-marshmallow
> Optimise service flaw ops

- CHANGELOG.md
- docs/tutorial.md
- griffon/output.py
- griffon/static/default_griffonrc
Define exclude_components in .griffonrc dotfile controlling which components to exclude from text output
> GRIF-70: add exclude_components to .griffonrc

- CHANGELOG.md
- scripts/smoke-tests.sh
>  griffon -vvv service products-contain-component -a libtiff
> added exclude_components to generating affects.

- griffon/commands/entities/corgi.py
- griffon/output.py
>griffon entities component-registry components tree --uuid baa16dae-3fc3-4251-b241-4b25439e0512 --show-purl | less
```
component dependency tree
┗━━ SOURCE: 
pkg:oci/redhat/ubi9-container@sha256:d0921af9841fc1e01273b7991d101e86afd355daefcc8b458ea46c71bcd5c4ad?repository_u
rl=registry.redhat.io/ubi9&tag=9.0.0-1640.1669730845
┣━━ PROVIDES: 
┃   pkg:oci/redhat/ubi9-container@sha256:329458d62365ffafd34c6e593872fa9dbfa41ffd2b4c5caa9f19453ff4bc0414?arch=ppc
┃   64le&repository_url=registry.redhat.io/ubi9&tag=9.0.0-1640.1669730845
┃   ┣━━ PROVIDES: pkg:rpm/redhat/libgcc@11.3.1-2.1.el9?arch=ppc64le
┃   ┣━━ PROVIDES: pkg:rpm/redhat/redhat-release@9.1-1.9.el9?arch=ppc64le
┃   ┣━━ PROVIDES: pkg:rpm/redhat/filesystem@3.16-2.el9?arch=ppc64le
┃   ┣━━ PROVIDES: …
```
> add component registry operation to display component dependency tree

- CHANGELOG.md
- griffon/commands/plugins/bugzilla.py
- griffon/commands/plugins/semgrep.py
> Add bugzilla plugin

- CHANGELOG.md
- griffon/cli.py
- griffon/commands/entities/corgi.py
- griffon/output.py
- griffon/services/core_queries.py
- griffon/static/default_griffonrc
GRIF-73: added --no-wrap option
GRIF-112: enhanced error handling when retrieving product stream/manifests
GRIF-108: fix regex searching
> GRIF-73, GRIF-112, GRIF-108

- griffon/static/default_griffonrc
Added few more patterns to exclude from default griffon output.
> added few more new patterns to exclude

- CHANGELOG.md
- griffon/__init__.py
> prep release v0.2.8

- CHANGELOG.md
- griffon/commands/queries.py
- griffon/output.py
- griffon/services/core_queries.py
- griffon/static/default_griffonrc
exposed in corgi (Defined in product definitions).
> GRIF-149: griffon will use exclude_components

- CHANGELOG.md
- griffon/output.py
exclude_products now works with regexes
> GRIF-155: fix exclude_products

- CHANGELOG.md
- griffon/commands/queries.py
- griffon/output.py
- griffon/services/__init__.py
- griffon/services/core_queries.py
--search-latest flag (which is set by default) should also search latest components in community.
while I was in the area, I added some statuses to make more visible griffon processing.
> GRIF-172: enable community searching of latest components.

- CHANGELOG.md
- griffon/__init__.py
* ensure we select released components
> prep test release v0.3.4

- CHANGELOG.md
- griffon/__init__.py
> Preparation of 0.3.5 release

- CHANGELOG.md
- griffon/commands/entities/helpers.py
- griffon/commands/entities/osidb.py
This PR adds support for CRUD operations for OSIDB entity Flaw Acknowledgments
> Flaw acknowledgements

- CHANGELOG.md
- griffon/__init__.py
> Preparation of 0.3.7 release

- CHANGELOG.md
- griffon/__init__.py
> Preparation of 0.3.8 release

- Makefile
- docs/operations.md
- scripts/helpers.sh
- scripts/release.sh
This PR introduces release script and entrypoint in `Makefile` as well as release docs adjustments to use aforementioned script.
> GRIF-194: Release scripts

- CHANGELOG.md
- griffon/__init__.py
> Preparation of 0.4.0 release

- CHANGELOG.md
- docs/user_guide.md
- griffon/__init__.py
To disable checking of ssl certs set
```
export GRIFFON_VERIFY_SSL=False
```
> added GRIFFON_VERIFY_SSL env var

- CHANGELOG.md
- griffon/__init__.py
> Preparation of 0.5.4 release
