- griffon/commands/queries.py
- griffon/services/core_queries.py
Return all components that depend on a specific component
```
> griffon service queries get-components-contain-component --purl "pkg:rpm/nmap@7.70"
```
returns
```
{
"link": "https://corgi-stage.prodsec.redhat.com/api/v1/components?purl=pkg%3Arpm/nmap%407.70",
"name": "nmap",
"purl": "pkg:rpm/nmap@7.70",
"sources": [
{
"link": "https://corgi-stage.prodsec.redhat.com/api/v1/components?purl=pkg%3Arpm/redhat/libabigail%402.1-2.el9%3Farch%3Dsrc",
"purl": "pkg:rpm/redhat/libabigail@2.1-2.el9?arch=src"
},
{
"link": "https://corgi-stage.prodsec.redhat.com/api/v1/components?purl=pkg%3Arpm/redhat/libabigail%402.1-1.el9%3Farch%3Dsrc",
"purl": "pkg:rpm/redhat/libabigail@2.1-1.el9?arch=src"
}
]
}
```
similarly, to return components by specifying just a name
```
> griffon service queries …
```
> GRIF-17 add get-components-contain-component service operation

- griffon/commands/entities.py
- griffon/commands/queries.py
- griffon/services/core_queries.py
Filter latest components for **ansible_automation_platform-2.2** by RPM type
```
>  griffon entities components list --ofuri o:redhat:ansible_automation_platform:2.2 --type RPM
```
to retrieve just its containers
```
> griffon entities components list --ofuri o:redhat:ansible_automation_platform:2.2 --type OCI
```
Filter returned sources by type
```
> griffon service queries get-components-contain-component --name nmap --type RPM
```
Similarly we can filter a single component's sources by type
```
> griffon service queries get-components-contain-component --purl "pkg:rpm/redhat/libarchive@3.3.3-3.el8_5?arch=aarch64" --type OCI
```
```
> griffon service queries get-components-contain-component --purl "pkg:rpm/redhat/libarchive@3.3.3-3.el8_5?arch=aarch64" --type RPM
```
> add --type filter

- griffon/commands/plugins/z_go_vuln.py
Search go vuln by go-id: 
```
griffon z_go_vuln get --id GO-2022-0189
```
Search go vuln by CVE-ID alias:
```
griffon z_go_vuln get --cve-id CVE-2018-16873
```
Or to do a general search 
```
griffon z_go_vuln search -q libcurl
```
> Add search by cve-id and general search to go_vuln plugin

- griffon/commands/queries.py
- griffon/services/core_queries.py
Add example report (with flags for --show-products and --show-components):
```
> griffon service reports affects --show-products
```
> example report

- griffon/__init__.py
- griffon/cli.py
- griffon/commands/configure.py
to initialise _~/.griffonrc_ and _~/.griffon/_
```
> griffon configure setup
```
which will create a ini dotfile at default location _~/.griffonrc_
following the normal ini file format 
```
[default]
format = text
[exclude]
```
> GRIF-30, add ~/.griffonrc file

- griffon/commands/queries.py
- griffon/output.py
inadvertently broke color formatting when implementing --no-color flag ... bringing it back. 
added back needed @click.passthru
> Minor: fix --no-color flag

- griffon/commands/queries.py
- griffon/services/core_queries.py
So we can invoke operations with regex search on name, for example
```
griffon service components-contain-component --re-name "^webkitgtk(\d)?$" | awk '{print $1}' | uniq
```
> add re-name to products-contain-component, components-contain-component

- griffon/output.py
- griffon/services/core_queries.py
enable --search-all, which returns both root components and dependencies.
> griffon service products-contain-component webkitgtk --search-all
> enable --search-all

- CHANGELOG.md
- griffon/__init__.py
`FlawResolutionEnum` and `AffectResolutionEnum` in osidb-bindings were changed to a kinda weird naming `Resolution01FEnum` and `Resolution3AcEnum`. This is due to a drf-spectacular which is responsible in schema creation in OSIDB to incorrectly resolve the naming clash.  We have a neat ways how to restrict these enums to not change the name in the future however this needs to be applied in OSIDB and thus another release is needed. Meanwhile we simply import new enums as a workaround.
> Fix OSIDB bindings usage

- CHANGELOG.md
Some additional lines were copied from osidb-bindings project during the changelog reformat, this PR removes them.
> Fix changelog description

- griffon/commands/entities/__init__.py
- griffon/commands/entities/component_registry.py
- griffon/commands/entities/osidb.py
- griffon/commands/queries.py
- requirements/base.in
- requirements/base.txt
- requirements/dev.txt
- requirements/test.txt
- setup.py
- tests/test_entities.py
refactored entrypoints to entities
> griffon entities OSIDB
> griffon entities CORGI
which makes it easy to create a shell alias, for example;
```
osidb-cli="griffon entities OSIDB"
```
> Refactor corgi entities

- CHANGELOG.md
- griffon/services/core_queries.py
default search uses --search-latest and --search-related-urls ... this speeds up the --search-related-urls bit
>griffon service products-contain-component -s kernel
> GRIF-71: speed up --search-related-urls

- griffon/output.py
- griffon/services/core_queries.py
narrow down products-contain-component text output to only contain significant component (ex. remove {component}-container if {component} exists as well).
> Various fixes

- griffon/output.py
Added default list when accessing dictionary with excluded components.
> Fix generating normalised results

- griffon/commands/queries.py
- griffon/output.py
- griffon/services/core_queries.py
which is similar to -e option in previous tool.
this filters components on specific type after the query.
> GRIF-94: add --output-type-filter

- .github/workflows/lint.yml
- CHANGELOG.md
- griffon/output.py
This adds regex filtering of components (in both prod defs and .griffonrc exclude_components) ... before we were matching if text is contained in component name.
While I was in the area, removed superfluous check on exclude component matches as we do this all in generate_normalised_results() function now.
> GRIF-149: add regex to component filtering

- CHANGELOG.md
- griffon/__init__.py
- griffon/commands/queries.py
griffon will not throw an error when using a partial .griffonrc, for example
```
[default]
output = text
[profile1]
details = foo
```
profile should not throw an error.
> GRIF-132: fix error thrown when using partial .griffonrc

- CHANGELOG.md
- griffon/helpers.py
- griffon/output.py
This PR fixes incorrect handling of product versions during the affect generation which resulted into processing only the first product version.
Also couple of debugging functions for developers were added so one can avoid repeated data heavy HTTP requests during the development.
Fixes GRIF-180
> Fix missing product versions during affect generation

- CHANGELOG.md
- griffon/output.py
Fixes the `TypeError: '<' not supported between instances of 'NoneType' and 'str'` for component-flaws query tracked in GRIF-115.
> Fix affect sorting with no CVE ID attached

- CHANGELOG.md
- griffon/commands/queries.py
- griffon/services/core_queries.py
Internal query services now leverage the ?provides_name= and ?re_provides_name= url params in component registry enabling direct searching on any components child dependencies.
**Note** - depends on a specific component-registry-bindings branch (pip install -e git+https://github.com/RedHatProductSecurity/component-registry-bindings.git@corgi-818-test#egg=component-registry-bindings
)
**Note**- depends on corgi deployment (to stage and prod)
Tests will fail until both of the above are addressed
> GRIF-72, GRIF-91, GRIF-173 provide searching on provides

- .github/workflows/lint.yml
Oddly enough, all actions using `tox` right now are currently erroring out. In #268 migration from `setup.py` to `pyproject.toml` was introduced which required tox to use `isolated_build=true` option. Apparently this option is present in tox from version 3.3.0 based on the docs, however we were running tox 3.24.5. I am no entirely sure how come that previously actions went OK and it is erroring out only now, but bumping the tox version should fir this problem.
> Bump tox version used in github workflows

- CHANGELOG.md
- docs/user_guide.md
- griffon/__init__.py
- griffon/cli.py
- griffon/commands/custom_commands.py
- griffon/commands/entities/community_component_registry.py
- griffon/commands/queries.py
- griffon/output.py
- griffon/services/core_queries.py
This PR:
* fixes the filtering of middleware CLI data
* standardize data (even upstreams and sources related data) to JSON in output module
> GRIF-130: Fix middleware CLI usage

- CHANGELOG.md
- griffon/commands/queries.py
- griffon/services/core_queries.py
This PR:
* fixes the non strict search which might contain some regex special characters to be regex escaped by default
* adds -r option for regex name search which will prevent the default escaping and will let user to take advantage of full regex search
* minor - fixes progress bar usage for product summary command
> GRIF-177: Fix non strict search

- CHANGELOG.md
- griffon/__init__.py
- griffon/commands/entities/community_component_registry.py
- griffon/commands/entities/corgi.py
- griffon/commands/entities/osidb/affects/__init__.py
- griffon/commands/entities/osidb/affects/cvss.py
- griffon/commands/entities/osidb/flaws/__init__.py
- griffon/commands/entities/osidb/flaws/acknowledgments.py
- griffon/commands/entities/osidb/flaws/comments.py
- griffon/commands/entities/osidb/flaws/cvss.py
- griffon/commands/entities/osidb/flaws/package_versions.py
- griffon/commands/entities/osidb/flaws/references.py
- griffon/commands/entities/osidb/trackers.py
- griffon/commands/process.py
- griffon/commands/queries.py
- griffon/commands/reports.py
- griffon/output.py
This PR:
* adds new parameters for `progress_bar` decorator, namely `is_updatable` and `initial_status` (see respective commits for extensive description)
* fixes errors of progress bar in several commands that were introduced in !270
* minor - fixes error in raw json transform
> GRIF-218: Fix operation status

- CHANGELOG.md
- griffon/commands/queries.py
- griffon/output.py
- griffon/services/core_queries.py
- griffon/static/default_griffonrc
- scripts/smoke-tests.sh
a heavy refactor of output from services products-contains-components
|  verbosity  | product                 | root                    | child           | other                                       | comment|
|---------------------|-------------------------|-----------------------|----------------|----------------------------------------|-------------|
|                         | product version    | nvr                      |                                       |                            |      default verbosity using product versions         |
| **-v**                    | product stream     | nvr (type)            |  [ name {versions} ({types}), ... ]  |            | uses product streams  includes children summarising versions, types              |
| **-vv**                   | …
> GRIF-209: refactor products-contains-component output and added --include-container-roots

- CHANGELOG.md
- griffon/commands/queries.py
- griffon/static/default_griffonrc
This PR:
* enables `--filter-rh-naming` by default
* makes `--filter-rh-naming` settable from the .griffonrc file
> GRIF-121 Filter RH naming by default

- CHANGELOG.md
- griffon/commands/queries.py
- griffon/output.py
- griffon/services/core_queries.py
a grab bag of random fixes ... mainly from diagnosing problems running smoke script.
> Minor fixes

- CHANGELOG.md
- griffon/commands/queries.py
- griffon/output.py
This PR:
* fixes a minor transform issue which added empty lists of related data even when these related data were not present
* fixes searches with middleware CLI as this got broken in [version 0.5.0](https://github.com/RedHatProductSecurity/griffon/releases/tag/0.5.0)
> GRIF-221: Fix output when using middleware CLI

- CHANGELOG.md
- griffon/commands/queries.py
- griffon/helpers.py
- griffon/output.py
- griffon/static/default_griffonrc
This PR:
* adds the `--deduplicate/--no-deduplicate` options for products-contain-component
* adds rhel/rhel-br deduplication step (GRIF-150)
* deduplicates results on verbosity level 0
* minor fixes - `-vvvv` with no  `GRIFFON_MIDDLEWARE_CLI` fix, latest NVR pick fix, naturally sorted product streams fix
> Result deduplication

- CHANGELOG.md
- griffon/__init__.py
This PR:
* deprecates old `*_API_URL` env variables in favor of `*_SERVER_URL` variables
* removes some unused progress bar code
> Deprecate old env variables
